# Databricks notebook source
print("an error has ocurred")
dbutils.notebook.exit(1)
